site_name: "python-app-wweewad"
site_description: "Main documentation for the python-app-wweewad"
repo_url: https://github.com/limhoooo/python-app-wweewad
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: "docs/index.md"
